routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'DashboardController@home')->name('home');

Route::get('dashboard', 'DashboardController@stats')->name('stats');

Route::resource('personnes', 'PersonneController');

Route::get('import', 'DashboardController@import')->name('import');
Route::post('import', 'DashboardController@processImport')->name('processImport');

app/Personne.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personne extends Model
{
    public $timestamps = false;
    protected $guardable = ['id'];
    protected $fillable = ['nom', 'prenom', 'sexe', 'naissance'];

    public function parents() {
        return $this->hasMany(__NAMESPACE__ . '\\Enfant');
    }

    public function marie() {
        return $this->hasMany(__NAMESPACE__ . '\\Marie');
    }

    public function acte() {
        return $this->hasOne(__NAMESPACE__ . '\\Acte', 'id_personne');
    }
}

app/Http/Controllers/PersonneController.php
<?php

namespace App\Http\Controllers;

use App\Personne;
use Illuminate\Http\Request;

class PersonneController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $personnes = Personne::take(100)->get();
        return view('personnes.index', compact('personnes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('personnes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $personne = Personne::create($request->all());
        return redirect(route('personnes.show', $personne));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $personne = Personne::find($id);
        return view('personnes.show', compact('personne'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $personne = Personne::findOrFail($id);
        return view('personnes.edit', compact('personne'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $personne = Personne::findOrFail($id);
        $personne->update($request->all());
        return redirect(route('personnes.edit', $personne));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $personne = Personne::destroy($id);
        return view('personne.destroy', compact('personne'));
    }
}

resources/views/personnes/create.blade.php
@extends('default')

@section('content')
    <h2>Ajouter une nouvelle personne</h2>
    {{ Form::open(['method' => 'post', 'url' => route('personnes.store')]) }}
    <div class="form-group">
        {{ Form::label('nom', 'Nom') }}
        {{ Form::text('nom', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('prenom', 'Prenom') }}
        {{ Form::text('prenom', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('sexe', 'Sexe') }}
        {{ Form::text('sexe', null, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('date', 'Date de naissance') }}
        {{ Form::date('date',null, ['class' => 'form-control']) }}
    </div>
    {{ Form::submit('Envoyer', ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/personnes/destroy.blade.php
@extends('default')

@section('content')
    <table class="table">
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Sexe</th>
            <th>Date naissance</th>
        </tr>
        <tr>
            <td>{{ $personne->nom }}</td>
            <td>{{ $personne->prenom }}</td>
            <td>{{ $personne->sexe }}</td>
            <td>{{ $personne->naissance }}</td>
        </tr>
    </table>
    <p>La personne <a href="bien été supprimée."></a></p>
    <a href="{{ route('personnes.index') }}" class="btn btn-primary">Retour sur l'index</a>
@endsection

resources/views/personnes/edit.blade.php
@extends('default')

@section('content')
    <h2>Editer une personne</h2>
    {{ Form::open(['method' => 'put', 'url' => route('personnes.update', $personne)]) }}
    <div class="form-group">
        {{ Form::label('nom', 'Nom') }}
        {{ Form::text('nom', $personne->nom, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('prenom', 'Prenom') }}
        {{ Form::text('prenom', $personne->prenom, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('sexe', 'Sexe') }}
        {{ Form::text('sexe', $personne->sexe, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('date', 'Date de naissance') }}
        {{ Form::date('date', $personne->naissance, ['class' => 'form-control']) }}
    </div>
    {{ Form::submit('Envoyer', ['class' => 'btn btn-primary']) }}
    {{ Form::close() }}
@endsection

resources/views/personnes/index.blade.php
@extends('default')

@section('content')
    <table class="table">
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Sexe</th>
            <th>Date naissance</th>
        </tr>
        @foreach($personnes as $personne)
            <tr>
                <td>{{ $personne->nom }}</td>
                <td>{{ $personne->prenom }}</td>
                <td>{{ $personne->sexe }}</td>
                <td>{{ $personne->naissance }}</td>
                <td><a class="btn btn-primary" href="{{ route('personnes.edit', $personne)}}">Editer</a></td>
                <td><a class="btn btn-danger" href="{{ route('personnes.destroy', $personne)}}">Supprimer</a></td>
            </tr>
        @endforeach
    </table>
    <a href="{{ route('personnes.create') }}" class="btn btn-primary">Créer une nouvelle personne</a>
@endsection

resources/views/personnes/show.blade.php
@extends('default')

@section('content')
    <table class="table">
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Sexe</th>
            <th>Date naissance</th>
        </tr>
        <tr>
            <td>{{ $personne->nom }}</td>
            <td>{{ $personne->prenom }}</td>
            <td>{{ $personne->sexe }}</td>
            <td>{{ $personne->naissance }}</td>
            <td><a class="btn btn-primary" href="{{ route('personnes.edit', $personne)}}">Editer</a></td>
        </tr>
    </table>
    <a href="{{ route('personnes.create') }}" class="btn btn-primary">Créer une nouvelle personne</a>
@endsection